table global500
	lineageTag: ca1a64a3-9eb8-4d8f-bc06-ee48c18dbd85

	column year
		dataType: string
		lineageTag: 7009be66-ce87-4cf4-bde7-c75bb71bf249
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: de8ed24a-7409-48be-9e30-b55f354c009b
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: int64
		formatString: 0
		lineageTag: 9c5ce26f-f174-4f69-a43d-fbea019388bd
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	column 'Revenues ($M)'
		dataType: double
		lineageTag: 5d41405f-b84b-485c-bfe4-b7eea1ac4e30
		summarizeBy: sum
		sourceColumn: Revenues ($M)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Revenue Percent Change'
		dataType: double
		lineageTag: 2e9ec593-911e-487b-8e06-a0e057bdcaa2
		summarizeBy: sum
		sourceColumn: Revenue Percent Change

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profits ($M)'
		dataType: double
		lineageTag: be0a3a94-2db3-4851-ac39-7f962eeda9ad
		summarizeBy: sum
		sourceColumn: Profits ($M)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Profits Percent Change'
		dataType: double
		lineageTag: 4707a620-a494-4f41-8c39-5aa6838c0862
		summarizeBy: sum
		sourceColumn: Profits Percent Change

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Assets ($M)'
		dataType: double
		lineageTag: 625421fb-6bb4-4bdc-bf51-4d65f5c52f68
		summarizeBy: sum
		sourceColumn: Assets ($M)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Newcomer to the Global 500'
		dataType: string
		lineageTag: 59816dcf-8e5f-4ea9-a7c8-939b1bdefdb2
		summarizeBy: none
		sourceColumn: Newcomer to the Global 500

		annotation SummarizationSetBy = Automatic

	column Employees
		dataType: int64
		formatString: 0
		lineageTag: 0b38d053-4594-4c84-980c-9adbf772e092
		summarizeBy: sum
		sourceColumn: Employees

		annotation SummarizationSetBy = Automatic

	column 'Dropped in Rank'
		dataType: string
		lineageTag: 1d943d2e-df8a-4942-af9d-38d5cde83667
		summarizeBy: none
		sourceColumn: Dropped in Rank

		annotation SummarizationSetBy = Automatic

	column 'Gained in Rank'
		dataType: string
		lineageTag: 338b8973-9628-43e0-984c-ca02eb90a472
		summarizeBy: none
		sourceColumn: Gained in Rank

		annotation SummarizationSetBy = Automatic

	column Sector
		dataType: string
		lineageTag: 38a85674-8563-47d6-8f5e-93d12f0fbe69
		summarizeBy: none
		sourceColumn: Sector

		annotation SummarizationSetBy = Automatic

	column Industry
		dataType: string
		lineageTag: 588cafb5-e59c-46de-bd62-f50bbf2ef5d3
		summarizeBy: none
		sourceColumn: Industry

		annotation SummarizationSetBy = Automatic

	column 'Country / Territory'
		dataType: string
		lineageTag: 3fc6c89d-799e-45b5-8d35-4b13a728287f
		summarizeBy: none
		sourceColumn: Country / Territory

		annotation SummarizationSetBy = Automatic

	column 'Headquarters City'
		dataType: string
		lineageTag: b49da18a-cf85-4391-9da9-00c60f6d4b2f
		summarizeBy: none
		sourceColumn: Headquarters City

		annotation SummarizationSetBy = Automatic

	column 'Headquarters State'
		dataType: string
		lineageTag: d4f39503-f17b-4a8e-94b9-7d9806ee1943
		summarizeBy: none
		sourceColumn: Headquarters State

		annotation SummarizationSetBy = Automatic

	column 'Years on Global 500 List'
		dataType: int64
		formatString: 0
		lineageTag: a9d8a3ea-f15f-47da-ab87-7152d8514376
		summarizeBy: sum
		sourceColumn: Years on Global 500 List

		annotation SummarizationSetBy = Automatic

	column Profitable
		dataType: string
		lineageTag: be7d4acc-25f5-4483-831e-23eee5f0afaa
		summarizeBy: none
		sourceColumn: Profitable

		annotation SummarizationSetBy = Automatic

	column 'World''s Most Admired Companies'
		dataType: string
		lineageTag: ea59a7ef-d715-4005-8525-6c9ab64ea978
		summarizeBy: none
		sourceColumn: World's Most Admired Companies

		annotation SummarizationSetBy = Automatic

	column 'Female CEO'
		dataType: string
		lineageTag: bd17da76-d7da-412b-bd62-502d13eef615
		summarizeBy: none
		sourceColumn: Female CEO

		annotation SummarizationSetBy = Automatic

	column 'Growth in Jobs'
		dataType: string
		lineageTag: 8f2b7dfa-0522-4c12-a065-bba289aa7937
		summarizeBy: none
		sourceColumn: Growth in Jobs

		annotation SummarizationSetBy = Automatic

	column 'Change the World'
		dataType: string
		lineageTag: a20517eb-7f2f-49b6-8f8f-397d58d9217e
		summarizeBy: none
		sourceColumn: Change the World

		annotation SummarizationSetBy = Automatic

	column 'Fastest Growing Companies'
		dataType: string
		lineageTag: f62c9bbc-5f99-4542-9514-a682cdfa229c
		summarizeBy: none
		sourceColumn: Fastest Growing Companies

		annotation SummarizationSetBy = Automatic

	column 'Fortune 500'
		dataType: string
		lineageTag: b4bde477-5607-4eaf-a08a-bde9add86c7d
		summarizeBy: none
		sourceColumn: Fortune 500

		annotation SummarizationSetBy = Automatic

	column 'Best Companies'
		dataType: string
		lineageTag: cc583b85-0598-4a31-96e5-5b5dfae3d967
		summarizeBy: none
		sourceColumn: Best Companies

		annotation SummarizationSetBy = Automatic

	column 'Non-U.S. Companies'
		dataType: string
		lineageTag: 73ebafd7-9985-46bd-aacc-99e7fd9a161a
		summarizeBy: none
		sourceColumn: Non-U.S. Companies

		annotation SummarizationSetBy = Automatic

	column 'Change in Rank'
		dataType: int64
		formatString: 0
		lineageTag: 24eaad9e-302a-4e0c-abc4-4c70a2dc65fd
		summarizeBy: sum
		sourceColumn: Change in Rank

		annotation SummarizationSetBy = Automatic

	partition global500 = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://fortune.com/api/getRankingSearchYear/global500/2023/")),
				    #"Converted to Table" = Table.FromRecords({Source}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Converted to Table",{"items", "year"}),
				    #"Expanded items" = Table.ExpandListColumn(#"Removed Other Columns", "items"),
				    #"Expanded items1" = Table.ExpandRecordColumn(#"Expanded items", "items", {"data", "name", "rank"}, {"data", "name", "rank"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded items1",{"year", "name", "rank", "data" }),
				    #"Expanded items.data" = Table.ExpandRecordColumn(#"Reordered Columns", "data", {"Revenues ($M)", "Revenue Percent Change", "Profits ($M)", "Profits Percent Change", "Assets ($M)", "Newcomer to the Global 500", "Employees", "Dropped in Rank", "Gained in Rank", "Sector", "Industry", "Country / Territory", "Headquarters City", "Headquarters State", "Years on Global 500 List", "Profitable", "World's Most Admired Companies", "Female CEO", "Growth in Jobs", "Change the World", "Fastest Growing Companies", "Fortune 500", "Best Companies", "Non-U.S. Companies", "Change in Rank"},  {"Revenues ($M)", "Revenue Percent Change", "Profits ($M)", "Profits Percent Change", "Assets ($M)", "Newcomer to the Global 500", "Employees", "Dropped in Rank", "Gained in Rank", "Sector", "Industry", "Country / Territory", "Headquarters City", "Headquarters State", "Years on Global 500 List", "Profitable", "World's Most Admired Companies", "Female CEO", "Growth in Jobs", "Change the World", "Fastest Growing Companies", "Fortune 500", "Best Companies", "Non-U.S. Companies", "Change in Rank"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded items.data",{{"rank", Int64.Type}, {"Assets ($M)", type number}, {"Profits Percent Change", Percentage.Type}, {"Profits ($M)", type number}, {"Revenue Percent Change", Percentage.Type}, {"Revenues ($M)", type number}, {"Employees", Int64.Type}, {"Years on Global 500 List", Int64.Type}, {"Change in Rank", Int64.Type}, {"Country / Territory", type text}, {"Headquarters City", type text}, {"Headquarters State", type text}, {"name", type text}, {"Newcomer to the Global 500", type text}, {"Dropped in Rank", type text}, {"Gained in Rank", type text}, {"Sector", type text}, {"Industry", type text}, {"Profitable", type text}, {"World's Most Admired Companies", type text}, {"Female CEO", type text}, {"Growth in Jobs", type text}, {"Change the World", type text}, {"Fastest Growing Companies", type text}, {"Fortune 500", type text}, {"Best Companies", type text}, {"Non-U.S. Companies", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

